# Generated by Django 5.0.9 on 2026-09-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Image externe, utilisée si aucun fichier n'est téléversé.",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Lien vers une vidéo (YouTube) illustrant la recette.",
            ),
        ),
    ]
