# Generated by Django 5.0.9 on 2026-09-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_thematicpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="root_recipe",
            field=models.ForeignKey(
                blank=True,
                help_text="None means this recipe IS a root. A forked recipe points at the same root as its source.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="recipes.recipe",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="version_label",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'Sans gluten', 'Version épicée'. Blank for the root recipe.",
                max_length=80,
            ),
        ),
    ]
