# Generated by Django 5.0.9 on 2026-09-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipe_root_recipe_recipe_version_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="thematicpage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="thematic_pages/"),
        ),
    ]
