# Generated by Django 5.0.9 on 2026-09-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_thematicpage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="content_publicly_licensed",
            field=models.BooleanField(
                default=False,
                help_text="Coché par l'auteur d'une recette importée (source_url renseignée) pour libérer l'accès public à son contenu rédactionnel (description/ingrédients/étapes). Sans effet sur une recette sans source_url, déjà pleinement publique.",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Saisie manuelle"),
                    ("url", "Import depuis une URL"),
                    ("cooklang", "Import Cooklang"),
                    ("youtube", "Import vidéo YouTube"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
