# Generated by Django 5.0.9 on 2026-09-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_reciperating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image_credit_author",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image_credit_license_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image_credit_note",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image_credit_source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image_license",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cc_by", "CC BY"),
                    ("cc_by_sa", "CC BY-SA"),
                    ("public_domain", "Domaine public / CC0"),
                    ("personal", "Photo personnelle (droits réservés à l'auteur)"),
                    ("permission", "Utilisée avec permission"),
                    ("unknown", "Non précisée"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recipestep",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipe_steps/"),
        ),
        migrations.AddField(
            model_name="recipestep",
            name="image_credit_author",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="recipestep",
            name="image_credit_license_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="recipestep",
            name="image_credit_note",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="recipestep",
            name="image_credit_source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="recipestep",
            name="image_license",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cc_by", "CC BY"),
                    ("cc_by_sa", "CC BY-SA"),
                    ("public_domain", "Domaine public / CC0"),
                    ("personal", "Photo personnelle (droits réservés à l'auteur)"),
                    ("permission", "Utilisée avec permission"),
                    ("unknown", "Non précisée"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recipestep",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
