# Generated by Django 5.0.9 on 2026-10-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_recipe_image_credit_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="content_publicly_licensed",
            field=models.BooleanField(
                default=False,
                help_text="Coché par l'auteur d'une recette importée (source_url renseignée), après avoir réécrit ses étapes et sa description avec ses propres mots, pour les rendre publiques. Sans effet sur une recette sans source_url, déjà pleinement publique.",
            ),
        ),
    ]
