# Generated by Django 5.0.9 on 2026-10-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_content_publicly_licensed_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="diet_type",
            field=models.CharField(
                choices=[
                    ("omnivore", "Flexitarien"),
                    ("vegetarian", "Végétarien"),
                    ("vegan", "Végan"),
                ],
                default="omnivore",
                max_length=20,
            ),
        ),
    ]
