# Generated by Django 5.0.9 on 2026-10-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_flexitarian_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cookware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=110, unique=True)),
                (
                    "translations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Noms dans d\'autres langues, ex. {"en": "oven"} — utilisé par la recherche et pour rapprocher le matériel d\'une recette importée.',
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True,
                        help_text="Un emoji représentant ce matériel, s'il en existe un, ex. 🍳",
                        max_length=8,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="cookware/")),
                (
                    "image_license",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cc_by", "CC BY"),
                            ("cc_by_sa", "CC BY-SA"),
                            ("public_domain", "Domaine public / CC0"),
                            ("personal", "Photo personnelle (droits réservés à l'auteur)"),
                            ("permission", "Utilisée avec permission"),
                            ("unknown", "Non précisée"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image_credit_author", models.CharField(blank=True, max_length=150)),
                ("image_credit_source_url", models.URLField(blank=True, max_length=500)),
                ("image_credit_license_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "cookware",
                "verbose_name_plural": "cookware",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="cookware",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="recipes.cookware"
            ),
        ),
    ]
