# Generated by Django 5.0.9 on 2026-10-04 16:04

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_cookware"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "emoji",
                    models.CharField(
                        blank=True,
                        help_text="Un emoji facultatif, ex. 🎂",
                        max_length=8,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("gray", "Gris"),
                            ("red", "Rouge"),
                            ("orange", "Orange"),
                            ("yellow", "Jaune"),
                            ("green", "Vert"),
                            ("teal", "Turquoise"),
                            ("blue", "Bleu"),
                            ("purple", "Violet"),
                            ("pink", "Rose"),
                        ],
                        default="gray",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipes",
                    models.ManyToManyField(
                        blank=True, related_name="personal_tags", to="recipes.recipe"
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.AddConstraint(
            model_name="personaltag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("owner"),
                name="unique_personal_tag_name_per_owner",
            ),
        ),
    ]
