# Generated by Django 5.0.9 on 2026-10-05 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0006_ingredient_created_by_ingredient_is_verified"),
        ("recipes", "0014_cookware_created_by_cookware_is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientAlternative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "gramme"),
                            ("kg", "kilogramme"),
                            ("ml", "millilitre"),
                            ("l", "litre"),
                            ("piece", "pièce"),
                            ("tbsp", "cuillère à soupe"),
                            ("tsp", "cuillère à café"),
                            ("pinch", "pincée"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("vegan", "Végan"),
                            ("vegetarian", "Végétarien"),
                            ("gluten_free", "Sans gluten"),
                            ("lactose_free", "Sans lactose"),
                            ("missing", "Si on n'en a pas"),
                            ("less", "Quantité réduite"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alternative_uses",
                        to="ingredients.ingredient",
                    ),
                ),
                (
                    "recipe_ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternatives",
                        to="recipes.recipeingredient",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="ingredientalternative",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("ingredient__isnull", True), ("tag", "less")),
                    models.Q(
                        models.Q(("tag", "less"), _negated=True),
                        ("ingredient__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="alternative_ingredient_matches_tag",
            ),
        ),
    ]
