# Generated by Django 5.0.9 on 2026-09-12 18:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vegetable", "Légume"),
                            ("fruit", "Fruit"),
                            ("legume", "Légumineuse"),
                            ("grain", "Céréale"),
                            ("nut_seed", "Noix / graine"),
                            ("dairy", "Produit laitier"),
                            ("meat_fish", "Viande / poisson"),
                            ("egg", "Œuf"),
                            ("fat", "Matière grasse"),
                            ("condiment", "Condiment / épice"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "default_unit",
                    models.CharField(
                        choices=[
                            ("g", "gramme"),
                            ("kg", "kilogramme"),
                            ("ml", "millilitre"),
                            ("l", "litre"),
                            ("piece", "pièce"),
                            ("tbsp", "cuillère à soupe"),
                            ("tsp", "cuillère à café"),
                            ("pinch", "pincée"),
                        ],
                        default="g",
                        max_length=10,
                    ),
                ),
                (
                    "available_months",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(),
                        blank=True,
                        default=list,
                        help_text="Mois (1-12) de pleine saison. Vide = disponible toute l'année.",
                        size=None,
                    ),
                ),
                (
                    "calories_kcal",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "carbs_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "fiber_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "iron_mg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "vitamin_b12_ug",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "calcium_mg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "omega3_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "zinc_mg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
