# Generated by Django 5.0.9 on 2026-09-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="carbon_kg_co2e_per_kg",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Empreinte carbone en kg CO2e par kg de produit (ordre de grandeur ACV).",
                max_digits=7,
            ),
        ),
    ]
