# Generated by Django 5.0.9 on 2026-09-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0002_ingredient_carbon_kg_co2e_per_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="translations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Noms de l\'ingrédient dans d\'autres langues, ex. {"en": "garlic", "de": "Knoblauch", "es": "ajo"} — utilisé pour rapprocher les ingrédients importés depuis une recette non francophone.',
            ),
        ),
    ]
