# Generated by Django 5.0.9 on 2026-09-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0004_search_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="ingredient",
            name="allergens_reviewed",
            field=models.BooleanField(
                default=False,
                help_text="Les allergènes ont été vérifiés. Faux = inconnu (ex. ingrédient créé à la volée ou importé) : l'absence d'allergène renseigné ne garantit rien.",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="allergens",
            field=models.ManyToManyField(
                blank=True, related_name="ingredients", to="ingredients.allergen"
            ),
        ),
    ]
