# Generated by Django 5.0.9 on 2026-10-04 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0005_allergen_ingredient_allergens_reviewed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_ingredients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="is_verified",
            field=models.BooleanField(
                default=True,
                help_text="Validé par un administrateur. Faux = créé par un utilisateur, à relire.",
            ),
        ),
    ]
