# Generated by Django 5.0.9 on 2026-09-20 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email"),
        ("ingredients", "0005_allergen_ingredient_allergens_reviewed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAllergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("allergy", "Allergie"),
                            ("intolerance", "Intolérance"),
                        ],
                        default="allergy",
                        max_length=20,
                    ),
                ),
                (
                    "allergen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ingredients.allergen",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergen_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="allergens",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                through="accounts.UserAllergen",
                to="ingredients.allergen",
            ),
        ),
        migrations.AddConstraint(
            model_name="userallergen",
            constraint=models.UniqueConstraint(
                fields=("user", "allergen"), name="unique_user_allergen"
            ),
        ),
    ]
