# Generated by Django 5.0.9 on 2026-10-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userallergen_user_allergens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="health_data_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="health_data_consent_version",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="inactivity_warned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
