# Generated by Django 5.0.9 on 2026-10-07 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_flexitarian_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_label", models.CharField(max_length=254)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("merge", "Fusion"),
                            ("hide_comment", "Commentaire masqué"),
                            ("unhide_comment", "Commentaire réaffiché"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_type", models.CharField(max_length=100)),
                ("target_id", models.CharField(blank=True, max_length=50)),
                ("target_label", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
