# Generated by Django 5.0.9 on 2026-10-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Avertissement"),
                            ("critical", "Critique (maintenance)"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(blank=True, max_length=120, verbose_name="titre (FR)"),
                ),
                (
                    "title_en",
                    models.CharField(blank=True, max_length=120, verbose_name="titre (EN)"),
                ),
                (
                    "message_fr",
                    models.TextField(blank=True, verbose_name="message (FR)"),
                ),
                (
                    "message_en",
                    models.TextField(blank=True, verbose_name="message (EN)"),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="URL complète ou chemin du site (ex. /blog).",
                        max_length=500,
                        verbose_name="lien",
                    ),
                ),
                (
                    "link_label_fr",
                    models.CharField(blank=True, max_length=60, verbose_name="libellé du lien (FR)"),
                ),
                (
                    "link_label_en",
                    models.CharField(blank=True, max_length=60, verbose_name="libellé du lien (EN)"),
                ),
                (
                    "dismissible",
                    models.BooleanField(
                        default=True,
                        help_text="Décochée : le bandeau reste affiché (ex. maintenance).",
                        verbose_name="peut être fermée",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="activée"),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Vide : visible tout de suite.",
                        null=True,
                        verbose_name="début",
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Vide : visible sans limite.",
                        null=True,
                        verbose_name="fin",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
