# Generated by Django 5.0.9 on 2026-10-04 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="link_url",
            field=models.CharField(
                blank=True,
                help_text="URL complète ou chemin du site (ex. /blog).",
                max_length=500,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(/(?!/)|https?://)",
                        "Un chemin du site (/blog) ou une URL http(s) uniquement.",
                    )
                ],
                verbose_name="lien",
            ),
        ),
    ]
