import pytest

from apps.ingredients.factories import IngredientFactory


@pytest.mark.django_db
def test_ingredient_slug_autogenerated():
    ingredient = IngredientFactory(name="Tomate cerise")
    assert ingredient.slug == "tomate-cerise"


@pytest.mark.django_db
def test_ingredient_in_season_year_round_when_no_months():
    ingredient = IngredientFactory(available_months=[])
    assert ingredient.is_in_season(month=1) is True


@pytest.mark.django_db
def test_ingredient_out_of_season():
    ingredient = IngredientFactory(available_months=[6, 7, 8])
    assert ingredient.is_in_season(month=1) is False
    assert ingredient.is_in_season(month=7) is True
