import pytest

from apps.ingredients.factories import IngredientFactory


@pytest.mark.django_db
def test_ingredient_slug_autogenerated():
    ingredient = IngredientFactory(name="Tomate cerise")
    assert ingredient.slug == "tomate-cerise"


@pytest.mark.django_db
def test_ingredient_in_season_year_round_when_no_months():
    ingredient = IngredientFactory(available_months=[])
    assert ingredient.is_in_season(month=1) is True


@pytest.mark.django_db
def test_ingredient_out_of_season():
    ingredient = IngredientFactory(available_months=[6, 7, 8])
    assert ingredient.is_in_season(month=1) is False
    assert ingredient.is_in_season(month=7) is True


@pytest.mark.django_db
def test_ingredient_translations_default_to_empty_dict():
    ingredient = IngredientFactory()
    assert ingredient.translations == {}


@pytest.mark.django_db
def test_ingredient_translations_store_arbitrary_locales():
    ingredient = IngredientFactory(translations={"en": "garlic", "de": "Knoblauch", "es": "ajo"})
    ingredient.refresh_from_db()
    assert ingredient.translations == {"en": "garlic", "de": "Knoblauch", "es": "ajo"}


@pytest.mark.django_db
def test_ingredient_slug_collision_gets_a_suffix():
    # "Tomate" et "tomate" produisent le même slugify() : le second ne doit pas
    # provoquer d'erreur d'intégrité mais obtenir un slug distinct.
    first = IngredientFactory(name="Tomate")
    second = IngredientFactory(name="tomate ")

    assert first.slug == "tomate"
    assert second.slug == "tomate-2"
