# Generated by Django 5.0.9 on 2026-09-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NutrientRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diet_type",
                    models.CharField(
                        choices=[
                            ("omnivore", "Omnivore"),
                            ("vegetarian", "Végétarien"),
                            ("vegan", "Végan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sédentaire"),
                            ("moderate", "Modéré"),
                            ("athlete", "Sportif"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nutrient",
                    models.CharField(
                        help_text="Doit correspondre à un champ nutritionnel d'Ingredient",
                        max_length=50,
                    ),
                ),
                ("unit", models.CharField(max_length=10)),
                ("daily_minimum", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                "unique_together": {("diet_type", "activity_level", "nutrient")},
            },
        ),
    ]
