# Generated by Django 5.0.9 on 2026-09-12 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingredients", "0001_initial"),
        ("planning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Liste de courses", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meal_plan_entries",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shopping_lists",
                        to="planning.mealplanentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "gramme"),
                            ("kg", "kilogramme"),
                            ("ml", "millilitre"),
                            ("l", "litre"),
                            ("piece", "pièce"),
                            ("tbsp", "cuillère à soupe"),
                            ("tsp", "cuillère à café"),
                            ("pinch", "pincée"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_owned", models.BooleanField(default=False)),
                ("is_checked", models.BooleanField(default=False)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shopping_list_items",
                        to="ingredients.ingredient",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shopping.shoppinglist",
                    ),
                ),
            ],
            options={
                "ordering": ["ingredient__category", "ingredient__name"],
                "unique_together": {("shopping_list", "ingredient", "unit")},
            },
        ),
    ]
